### ISSUE TITLE
instance of Fn::GetAtt references undefined resource

### ISSUE THREAD

**Issue by Negan1911** [dougmoscrop/serverless-plugin-split-stacks#150]
Hi, after updating from `1.9.3` to `1.10.0` i started to receive this following error on my deploys:

```bash
 Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource QueryUnderscoreConversationLambdaFunction
      at /home/runner/work/projectapi/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/home/runner/work/projectapi/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/runner/work/projectapi/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/runner/work/projectapi/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/runner/work/projectapi/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/runner/work/projectapi/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/home/runner/work/projectapi/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/runner/work/projectapi/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/runner/work/projectapi/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/projectapi/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```

After reverting back to `1.9.3` it returns to normal.
Let me know if any more info is needed, not quite sure on which detail I can contribute to solve this error!

Thanks!

**Comment by gilad-embryonics** [comment]
how is it possible to revert to 1.9.3 in the serverless.yml file?

**Comment by vicary** [comment]
We have been reducing for a repeatable use case for weeks already. Trying commit by commit, it is cycling back and forth between this bug and circular dependency.

**Comment by Negan1911** [comment]
I'll try to point my project to specific commits to see if I can found which one is causing it

**Comment by mnickkk** [comment]
@Negan1911 
I think these changes are causing the issues:
https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/master/lib/utils.js#L243
https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/master/lib/utils.js#L248

context for ref: https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/147#issuecomment-747962069

**Comment by vicary** [comment]
@mnickkk I want to fix this in my fork and possibly make a PR if none if the release branches here fixes the issue, but I don't think I understand the underlying cause enough.

Is `cloneDeep` doing its job correctly?

My current best guess is that `cloneDeep` does not resolves object references for migration utilities to know that when target resources are eventually allocated into different stacks, they should be hoisted into `<Output>` and `<Paramaters>` at root stack.

**Comment by thadeu** [comment]
Hi guys, something about this? I'm has been same problem as well. I'd like so much help with problem. 
I appreciate so much the library, but my deploy dont work for this.
