### ISSUE TITLE
Issue with version 1.3.0

### ISSUE THREAD

**Issue by selected-pixel-jameson** [dougmoscrop/serverless-plugin-split-stacks#17]
Having an issue with the latest version. This is the log is spitting out on my build server.
```
  Type Error ---------------------------------------------

  Cannot use 'in' operator to search for 'Fn::GetAtt' in xxxxxxxx

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot use 'in' operator to search for 'Fn::GetAtt' in xxxxxx
at Reference.getDependencyName (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/lib/reference.js:10:22)
at Object.ResourceMigrated (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/lib/replace-references.js:19:55)
at ServerlessPluginSplitStacks.reconcile (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/lib/utils.js:236:25)
at _.each.dependency (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/lib/replace-references.js:16:12)
at arrayEach (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/lodash/lodash.js:537:11)
at Function.forEach (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/lodash/lodash.js:9359:14)
at _.each (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/lib/replace-references.js:15:7)
at /home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/lodash/lodash.js:4944:15
at baseForOwn (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/lodash/lodash.js:3001:24)
at /home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/lodash/lodash.js:4913:18
at Function.forEach (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/lodash/lodash.js:9359:14)
at ServerlessPluginSplitStacks.replaceReferences (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/lib/replace-references.js:6:5)
at Promise.resolve.then.then.then (/home/rof/src/bitbucket.org/healthtalks/xxxxxxxxxxx/node_modules/serverless-plugin-split-stacks/split-stacks.js:69:24)
at <anonymous>
From previous event:
at PluginManager.invoke (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
at PluginManager.spawn (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:384:17)
at AwsPackage.BbPromise.bind.then (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/aws/package/index.js:69:51)
From previous event:
at Object.package:finalize [as hook] (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/aws/package/index.js:69:10)
at BbPromise.reduce (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
at PluginManager.invoke (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
at PluginManager.spawn (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:384:17)
at Deploy.BbPromise.bind.then.then (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:120:50)
From previous event:
at Object.before:deploy:deploy [as hook] (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:110:10)
at BbPromise.reduce (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
at PluginManager.invoke (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
at PluginManager.run (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
at variables.populateService.then (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/Serverless.js:104:33)
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at Serverless.run (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/Serverless.js:91:74)
at serverless.init.then (/home/rof/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/bin/serverless:42:50)
at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.1
     Serverless Version:     1.24.1
```

**Comment by dougmoscrop** [comment]
Sorry I will look in to it!

**Comment by dougmoscrop** [comment]
Can you try 1.3.1?

**Comment by selected-pixel-jameson** [comment]
Seems to work with 1.3.1. Thanks for the outstandingly quick response.
