### ISSUE TITLE
Cannot read property 'match' of null

### ISSUE THREAD

**Issue by webjay** [dougmoscrop/serverless-plugin-split-stacks#71]
I get `Cannot read property 'match' of null` when I use `1.8.0` but not with `1.7.x`.

I use these plugins:

    "serverless": "1.46.0",
    "serverless-domain-manager": "3.2.6",
    "serverless-plugin-warmup": "4.5.3-rc.1",
    "serverless-plugin-split-stacks": "1.7.x"

Here's a trace:

    Serverless: Invoke deploy
    Serverless: Invoke package
    Serverless: Invoke aws:common:validate
    Serverless: Invoke aws:common:cleanupTempDir
    Serverless: WarmUp: no functions to warm up
    Serverless: Packaging service...
    Serverless: Excluding development dependencies...
    Serverless: Invoke aws:package:finalize
    
      Type Error ---------------------------------------------
    
      Cannot read property 'match' of null
    
        For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
    
      Stack Trace --------------------------------------------
    
    TypeError: Cannot read property 'match' of null
        at dnsCompatible (/Users/jacob/Sites/api2/node_modules/serverless-plugin-split-stacks/lib/deployment-bucket-endpoint.js:6:38)
        at Promise (/Users/jacob/Sites/api2/node_modules/serverless-plugin-split-stacks/lib/deployment-bucket-endpoint.js:26:11)
        at new Promise (<anonymous>)
        at ServerlessPluginSplitStacks.setDeploymentBucketEndpoint (/Users/jacob/Sites/api2/node_modules/serverless-plugin-split-stacks/lib/deployment-bucket-endpoint.js:22:12)
        at Promise.resolve.then (/Users/jacob/Sites/api2/node_modules/serverless-plugin-split-stacks/split-stacks.js:59:24)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by dougmoscrop** [comment]
Thanks for the stack trace, should be able to fix quickly.

**Comment by kevlarr** [comment]
Just ran into this with `1.9.0` as well, similar stack trace

**Comment by dougmoscrop** [comment]
I think I see the bug, but dunno for sure - is your `deploymentBucket:` config an object instead of a string? If so, please try `1.9.1`, if not please post as much of your serverless.yml as you can

**Comment by webjay** [comment]
It works with `1.9.1`. Thank you.

**Comment by kevlarr** [comment]
Same, was an object instead of a string
